### ISSUE TITLE
Document how to mount non-home-dir

### ISSUE THREAD

**Issue by bnordgren** [irods/irods_client_fuse#10]
Looking at the docs, and '-h', I don't see how to mount directories other than the home directory. A little experimentation indicates to me that perhaps it just mounts your iRODS current working directory (output of ipwd) to whatever mountpoint you specify. I assume that the example in the documentation mounts the home directory merely because there is no "icd" shown.

**Comment by iychoi** [comment]
With current release of irodsFs, you can change your mount directory with `icd`. irodsFs will use current working directory (a result of `ipwd`) as its mount directory.
I already made a fix for this at #8

**Comment by bnordgren** [comment]
I figured that out through experimentation. ;) This ticket is about adding this information to the documentation so blind trial and error isn't necessary. :)

**Comment by iychoi** [comment]
I will ellaborate the help docs at future commits.
