### ISSUE TITLE
new dataobject via fusemount not triggering replication

### ISSUE THREAD

**Issue by trel** [irods/irods_client_fuse#12]
see https://github.com/irods/irods/issues/3103 for discussion.

**Comment by iychoi** [comment]
I've seen the issue and discussion for it. The irodsfs currently uses following C APIs to write a file:
- rcDataObjCreate
- rcDataObjOpen
- rcDataObjWrite
- rcDataObjClose

I haven't seen any options/flags allowing me to enable the replication. Is there a flag for it? Or Do I need to call `rcDataObjRepl` function for it?

**Comment by trel** [comment]
I believe the oprType is the key...

[Similar code in python library](https://github.com/irods/python-irodsclient/blob/c34d78173209f98c976e75ffe752521d53827a82/irods/connection.py#L319-L334)

@jasoncoposky this correct?

**Comment by iychoi** [comment]
I see the `oprType` is set to `0` in the python library. And `irodsFs` has `0` too.

**Comment by iychoi** [comment]
@xu-hao said there are two ways of setting the replication, 1) via `acPostProcForPut` and 2) via `resource hierarchy`.
It seemed `acPostProcForPut` is called properly at write. So I guess @JosKer29 used the latter. Is this correct?

**Comment by JosKer29** [comment]
Hello, 
For my part I use the 2nd way (resource hierarchy). I have 3 servers and I want to replicate my data on this 3 servers. 

This my resource tree : 
```
root_BDR_Resc:passthru
└── repli_BDR_Resc:replication
    ├── FSRe_BDR_Resc:unixfilesystem
    ├── FSRo_BDR_Resc:unixfilesystem
    └── FSNa_BDR_Resc:unixfilesystem
```
Best regards, 
Joseph

**Comment by iychoi** [comment]
@JosKer29 Can you try the same test with `python-irodsclient`? I guess the cause of this is in the C APIs.

**Comment by JosKer29** [comment]
@iychoi yes it's possible but i don"t know how i can do that with `python-irodsclient ` ? 

The issue is when i put data object in the fuse directory.

**Comment by adetorcy** [comment]
The `oprType` kicks in in `rsDataObjClose` but must be set when opening the object (i.e when calling `rc/rsDataObjOpen`).
For example with PRC:
https://github.com/irods/python-irodsclient/blob/master/irods/manager/data_object_manager.py#L63
PEP test:
https://github.com/irods/python-irodsclient/blob/master/irods/test/data_obj_test.py#L316-L383

**Comment by JosKer29** [comment]
Hello, 
I have tested with `python-irodsclient` (with the `data_objects.put()` function) and my file is replicated. 
I have retried with the last version of `irods-fuse` and still have the same issue. 
I have tried with a `cp`, `mv `and create file directly in folder and file is not replicate each time.

**Comment by iychoi** [comment]
Hi @JosKer29.
Thanks for the test. Can you reperform the test with `write()` function instead of `put()` function? They are handled differently so I am not sure it is really fixed in `python-irodsclient` in the setting.

**Comment by trel** [comment]
Pretty sure this is now handled by the server much better since 2018.   Closing.
