### ISSUE TITLE
Can't build with irods version 4.2.2?

### ISSUE THREAD

**Issue by jwhitney31337** [irods/irods_client_fuse#13]
I'm trying to follow the build instructions on Ubuntu 14.04, I installed all the prereq packages and had previously installed irods using the icommands client deb from here: https://irods.org/download/

When I run cmake I get this:
$ cmake ..
CMake Error at CMakeLists.txt:3 (find_package):
  Could not find a configuration file for package "IRODS" that exactly
  matches requested version "4.2.0".

  The following configuration files were considered but not accepted:

    /usr/lib/irods/cmake/IRODSConfig.cmake, version: 4.2.2

-- Configuring incomplete, errors occurred!

I assume that the problem is that my irods installation (which provides /usr/lib/irods/cmake/IRODSConfig.cmake) is too new.  I could of course uninstall and try to get irods 4.2.0 installed, but I'm thinking the right thing would be for this package (irods_client_fuse) to be updated to work with 4.2.2.  Is this an easy fix?  I didn't want to "cheat" by changing my file to put in a bogus version number in case that introduces subtle issues.
Would appreciate any advice on a workaround meanwhile.

Cheers,

Joe

**Comment by trel** [comment]
The first step would be to change the version that is required by this project to say '4.2.2'.

Please try that first - it just might work (and of course, let us know).

**Comment by jwhitney31337** [comment]
Seems to work, thanks!
I've got a mount working for my current irods collection.

**Comment by trel** [comment]
Excellent.
