### ISSUE TITLE
Can't open FileChannel to irods-mounted file

### ISSUE THREAD

**Issue by jwhitney31337** [irods/irods_client_fuse#14]
I assume this has to do with an underlying mmap call that isn't supported.  This came up when trying to access a bam file using its associated index file (.bai) using [IGV](https://github.com/igvteam/igv).

I isolated the problem to the following test case.
Java code test.java:
import java.nio.channels.FileChannel;
import java.io.RandomAccessFile;
import java.nio.MappedByteBuffer;
import java.io.FileInputStream;
import java.io.File;
public class test {
public static void main(String args[]) throws Exception{
FileInputStream fileStream = new FileInputStream(new File(args[0]));
FileChannel      inChannel = fileStream.getChannel();
System.out.println("inChannel.size():"+inChannel.size());
MappedByteBuffer mFileBuffer = inChannel.map(FileChannel.MapMode.READ_ONLY, 0L, inChannel.size());
}
}

compile:
javac test.java

run:
java test /mnt/irods/path/to/some/file

result:
inChannel.size():8778992
Exception in thread "main" java.io.IOException: No such device
	at sun.nio.ch.FileChannelImpl.map0(Native Method)
	at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:926)
	at test.main(test.java:11)

I really hope this can be fixed, please let me know if I can help diagnose further.  I have quite a bit of java experience but not so much with irods & fuse.

**Comment by iychoi** [comment]
Can you tell me what version of FUSE did you use?

**Comment by jwhitney31337** [comment]
Looks like:
$ apt-cache show fuse|grep Version
Version: **2.9.2**-4ubuntu4.14.04.1
Version: **2.9.2**-4ubuntu4

**Comment by iychoi** [comment]
It looks like a cause of this issue is in FUSE itself. It seems there is a patch for this but somehow it is not merged to the master repo. Check out following link for information. 

https://sourceforge.net/p/fuse/mailman/message/32034582/

**Comment by jwhitney31337** [comment]
I read the link, my understanding is that the underlying limitation has to do with writeable shared memorymap, not basic read-only mmap.

More importantly, I know this problem is not universal to fuse filesystems, because I can mount the same file over sshfs and IGV is able to use it just fine (and my java test above runs without throwing an exception).

**Comment by iychoi** [comment]
It can be the result of ["direct_io" flag](https://github.com/irods/irods_client_fuse/blob/master/src/irodsFs.cpp#L76) used in the irodsFs. I'll investigate it later (maybe during the year-end holidays).

**Comment by jwhitney31337** [comment]
Ah, removing direct_io indeed fixes the problem -- I rebuilt after commenting out that one line, and now both my test case above and my original case above seem to be working fine.

Without knowing the history, it seems odd to have this option hard-coded when it can already be specified on command line.  Would the right thing to do be simply to remove this?  Otherwise, adding a different option to irodsFs that lets you skip this behaviour would be the second best option.

**Comment by iychoi** [comment]
Thanks for the test. 

The reason, I hardcoded the direct_io flag was to ensure cache consistency. Becase irodsFs has its own caching mechanism, it doesn't need to use os level page caching so that the direct_io disables it. Enabling the os level page caching may result in inconsistent state at concurrent I/O so I disabled it.

I'll add a new option that allows users to disable the direct_io flag (which will enable os level page caching).

**Comment by jwhitney31337** [comment]
Great!  We are only interested in read-only mounts so the cache consistency should not be an issue, do you agree?

**Comment by iychoi** [comment]
In my understanding, read-only mounts will not cause cache inconsistency. So it will be okey.

**Comment by iychoi** [comment]
The update is contained at #18
