### ISSUE TITLE
using irodsFs before iinit should either return an error or create the necessary .irodsA file

### ISSUE THREAD

**Issue by edwins** [irods/irods_client_fuse#16]
Given the following situation:

* a correctly defined irods_environment.json in $HOME/.irods
* iinit was not performed (so no $HOME/.irods/.irodsA was created)

Perform the following steps:
1. execute irodsFs
2. after the password prompt, enter password
3. attempt to perform a directory listing. should receive the following error:

`dir: cannot open directory 'mydirectory': Input/output error`

Ideally, the user should be informed that iinit should be performed, rather than continuing with a password prompt. Alternatively, create the necessary .irodsA file after authenticating.

This is a bug reported on behalf of another user.

**Comment by iychoi** [comment]
I'll check this as soon as I have time to work for this. The password prompt is not given by my code so I assume it is the default behavior of the iRODS C API which irodsFs relies on. I think I can check if the username and password is retrievable right after irodsFs starts and raises an error if they do not exist.

Thanks for the report.

**Comment by trel** [comment]
We'll be archiving this repository.

A new implementation of a fuse client for iRODS is now here:

https://github.com/cyverse/irodsfs
