### ISSUE TITLE
typo in irodsFs option causes a segmentation fault

### ISSUE THREAD

**Issue by edwins** [irods/irods_client_fuse#17]
We noticed that a typo in one of the options will cause irodsFs will crash. For example:

`$ irodsFs -oallow_other -oconnreuse -ometatdatacachetimeout 3600 -opreloadblocks 5 $HOME/data_home
Segmentation fault (core dumped)`

In this case, there is an extra letter t in the metadatacachetimeout option. To the extent possible, the irodsFs should validate the options and report any issues to the user and not segfault.

A couple of other nice-to-have suggestions: it would be nice to have an updated help with the current options on -h and to have both short and long forms for options (so that users don't have to type 'metadatacachetimeout').

Thank you!

**Comment by iychoi** [comment]
Thanks for the report. I'll fix this at a next push (maybe nextweek?).

**Comment by iychoi** [comment]
The update is contained at #18
