### ISSUE TITLE
usability issue: uppercase letter in binary

### ISSUE THREAD

**Issue by c-mart** [irods/irods_client_fuse#19]
```
root@cmart-macpro:~# irodsfs
irodsfs: command not found
```

What? _reinstalls package_

```
root@cmart-macpro:~# irodsfs
irodsfs: command not found
```

... :frowning_face:

_looks at docs_

Oh, irods**F**s.

```
root@cmart-macpro:~# ls -1 /usr/bin | grep -v "[A-Z]" | wc -l
1332
root@cmart-macpro:~# ls -1 /usr/bin | grep "[A-Z]" | wc -l
16
```

Of the 1348 binaries in my `/usr/bin`, 99% of them contain no upper-case letters. What justifies the usability cost of breaking convention here?

**Comment by trel** [comment]
Agreed - will look at the best way to change this and not break backwards compatibility

**Comment by trel** [comment]
We'll be archiving this repository.

Please use a new implementation which is more stable and maintained and addresses this issue.

https://github.com/cyverse/irodsfs
