### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by BlakeGFitch** [irods/irods_client_fuse#20]
Hi All,

This project looks interesting but there doesn't seem to be much activity. Is this project still active and/or in use by anyone? If not, are there reasons why not?

Thanks,
Blake

**Comment by trel** [comment]
Hi Blake,

There are some inherent limitations in the fuse protocol (handling multiple users, caching, errors / disaster recovery) that have been incorporated into the WebDAV protocol.

The davrods project from Utrecht is where the users of this fuse client migrated...

https://github.com/UtrechtUniversity/davrods

**Comment by BlakeGFitch** [comment]
Thanks! I will have a look.

**Comment by trel** [comment]
We'll be archiving this repository.

A new implementation of a fuse client for iRODS is now here:

https://github.com/cyverse/irodsfs
